### ISSUE TITLE
Submenu items example

### ISSUE THREAD

**Issue by eugenevk** [nitintutlani/angular-ui-router-menus#12]
Hi Nitin,

Can you please provide an example on how to use a tree menu with child items? I'm having trouble to make that work. Don't know how to define a submenu for a menu item.

Thanks,
Eugene

**Comment by nitintutlani** [comment]
Readme.md has an example on tree. PS: UI router states are defined hierarchically. This plug-in only iterates them using .children property.

**Comment by eugenevk** [comment]
But how do you define the state for a sub-menu and how can you render a sub-menu as nicely as a main menu item (for which I am using "nav bs-docs-sidenav")?

**Comment by nitintutlani** [comment]
If states are defined hierarchically, the `type="tree"` menu will be hierarchical automatically. Ability to implement menu styling and indentation is beyond the scope of this plugin.
